### PR TITLE
Create basic test environment

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by iamcco** [comment]
Thank you!

**Comment by przepompownia** [comment]
Thanks for merging! It may be helpful for any future changes.

**Comment by przepompownia** [comment]
Setting up Circle, Travis or any other CI environment in this project would be appreciated.

**Comment by iamcco** [comment]
> Thanks for merging! It may be helpful for any future changes.

Yes, well done.

> Setting up Circle, Travis or any other CI environment in this project would be appreciated.

I will do it when have time.

**Pull request merged**
